// TemplateRuntime
export const HTML_TEMPLATE_1 = 'HtmlTemplate1'
export const HTML_TEMPLATE_2 = 'HtmlTemplate2'
export const HTML_TEMPLATE_3 = 'HtmlTemplate3'
export const HTML_CAROUSEL_TEMPLATE = 'HtmlCarouselTemplate'
export const HTML_PLAYER_INFO = 'HtmlPlayerInfo'
// UiComponent (Vue Component)
export const ALEXA_COMMS_TEMPLATE = 'AlexaCommsTemplate'
export const BODY_TEMPLATE_1 = 'BodyTemplate1'
export const BODY_TEMPLATE_2 = 'BodyTemplate2'
export const LIST_TEMPLATE_1 = 'ListTemplate1'
export const LOCAL_SEARCH_LIST_TEMPLATE_1 = 'LocalSearchListTemplate1'
export const LOCAL_SEARCH_DETAIL_TEMPLATE_1 = 'LocalSearchDetailTemplate1'
export const WEATHER_TEMPLATE = 'WeatherTemplate'
export const RENDER_PLAYER_INFO = 'RenderPlayerInfo'
export const ALARM_COMES_DUE = 'AlarmComesDue'
export const TIMER_IS_DONE = 'TimerIsDone'
export const REMINDER_COMES_DUE = 'ReminderComesDue'
// In-App
export const WELCOME_CARD = 'WelcomeCard'
export const ALEXA_MENU = 'AlexaMenu'
export const ALEXA_MENU_SETTINGS = 'AlexaMenuSettings'
export const ALEXA_MENU_SETTINGS_CONTACT_LIST = 'AlexaMenuSettingsContactList'
export const ALEXA_MENU_SETTINGS_HANDSFREE_LISTENING = 'AlexaMenuSettingsHandsfreeListening'
export const ALEXA_MENU_SETTINGS_NOTIFICATIONS = 'AlexaMenuSettingsNotifications'
export const ALEXA_MENU_SETTINGS_START_OF_REQUEST_SOUND = 'AlexaMenuSettingsStartOfRequestSound'
export const ALEXA_MENU_SETTINGS_END_OF_REQUEST_SOUND = 'AlexaMenuSettingsEndOfRequestSound'
export const ALEXA_MENU_THINGS_TO_TRY = 'AlexaMenuThingsToTry'
export const ALEXA_MENU_THINGS_TO_TRY_DETAIL = 'AlexaMenuThingsToTryDetail'
export const ALEXA_MENU_LANGUAGE = 'AlexaMenuLanguage'
